name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get install python2.7
    - run: sudo apt-get install build-essential
    - run: npm i enmap@latest
    - run: npm i discord.js
    - run: npm i chalk
    - run: npm i better-sqlite-pool
    - run: npm i moment-duration-format
    - run: npm i klaw
    - run: npm i moment
    - run: node index.js
      env:
        CI: true
